Repository apache/kylin, pull requests merged in 2020-09, with the labels that each got.

#1360 KYLIN-4688 Too many tmp files in HDFS tmp dictionary
  core-common/src/main/java/org/apache/kylin/common/util/HadoopUtil.java
  storage-hbase/src/main/java/org/apache/kylin/storage/hbase/steps/CubeHFileJob.java
Labels: Ready to merge

#1373 KYLIN-4716 Optimize the project page
  webapp/app/js/model/projectConfig.js
  webapp/app/partials/projects/projects.html
Labels: Reviewing

#1340 KYLIN-4679 StorageCleanupJob clean hive table support hive table prefix
  core-common/src/main/java/org/apache/kylin/common/util/HiveCmdBuilder.java
  server-base/src/main/java/org/apache/kylin/rest/job/StorageCleanupJob.java
  source-hive/src/main/java/org/apache/kylin/source/hive/BeelineHiveClient.java
Labels: Reviewing

#1370 KYLIN-4714 Failed to revoke role access of the project
  server-base/src/main/java/org/apache/kylin/rest/service/AclService.java
  server/src/test/java/org/apache/kylin/rest/controller/AccessControllerTest.java
  server/src/test/java/org/apache/kylin/rest/service/AccessServiceTest.java
Labels: Reviewing

#1351 KYLIN-4683 Fail to consume kafka when partition number get larger
  stream-source-kafka/src/main/java/org/apache/kylin/stream/source/kafka/consumer/KafkaConnector.java
Labels: In Progress
